services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
      - ..:/var/www/html:rw
    depends_on:
      - php

  php:
    build: ..
    volumes:
      - ..:/var/www/html:rw
      - db_data:/var/www/html/database
    working_dir: /var/www/html

volumes:
  db_data: